"""empty message

Revision ID: 74ce86fd6113
Revises: bf5042a0b251
Create Date: 2022-08-08 20:03:35.326003

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74ce86fd6113'
down_revision = 'bf5042a0b251'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artists', sa.Column('seeking_venue', sa.Boolean(), nullable=False))
    op.add_column('artists', sa.Column('seeking_description', sa.String(), nullable=True))
    op.drop_column('artists', 'seek_decription')
    op.drop_column('artists', 'looking_talent')
    op.add_column('venues', sa.Column('seeking_talent', sa.Boolean(), nullable=False))
    op.add_column('venues', sa.Column('seeking_description', sa.String(), nullable=True))
    op.drop_column('venues', 'seek_decription')
    op.drop_column('venues', 'looking_talent')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venues', sa.Column('looking_talent', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('venues', sa.Column('seek_decription', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('venues', 'seeking_description')
    op.drop_column('venues', 'seeking_talent')
    op.add_column('artists', sa.Column('looking_talent', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('artists', sa.Column('seek_decription', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('artists', 'seeking_description')
    op.drop_column('artists', 'seeking_venue')
    # ### end Alembic commands ###
